# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Lint
    jobs:
      - job: LintCode
        steps:
          - script: |
              echo "Lintinggg ..."
              ./gradlew check
            displayName: 'Code validation using Gradle'

  - stage: UnitTest
    jobs:
      - job: RunUnitTests
        steps:
          - script: |
              echo "Running unit testing"
              ./gradlew test
            displayName: 'Code testing using Gradle'
