trigger:
- main
- azure-pipelines

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Lint
    jobs:
      - job: LintCode
        steps:
          - script: |
              echo "Lintinggg ..."
              ./gradlew check
            displayName: 'Code validation using Gradle'

  - stage: UnitTest
    jobs:
      - job: RunUnitTests
        steps:
          - script: |
              echo "Running unit testing"
              ./gradlew test
            displayName: 'Code testing using Gradle'
