trigger:
- main
- azure-pipelines

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Lint
    jobs:
      - job: LintCode
        steps:
          - script: |
              echo "Lintinggg ..."
              ./gradlew check
            displayName: 'Code validation using Gradle'

  - stage: UnitTest
    jobs:
      - job: RunUnitTests
        steps:
          - script: |
              echo "Running unit testing"
              ./gradlew test
            displayName: 'Code testing using Gradle'
            
  - stage: SonarQube
    jobs:
      - job: Sonar_SAST_Scan_Job
        container: openjdk:18-jdk-slim
        steps:
          - script: |
              echo "Running Jacoco testing"
              ./gradlew test jacocoTestReport sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=3omda1‬‏ -Dsonar.projectKey=3omda1_DevSecOps-With-Azure -Dsonar.token=4f61374d9dce0c8447de2bcb062f83df66958463
            displayName: 'Integrate SAST using SonarCloud to populate code coverage'
